### ISSUE TITLE
Error while calling the program

### ISSUE THREAD

**Issue by FlorianHubl** [jerryfletcher21/roboauto#1]
I installed the programm exactly how it's described. But when I try this command:
`roboauto --help`
I get this error:
`Traceback (most recent call last):
  File "/Users/florian/Downloads/roboauto/robo/bin/roboauto", line 9, in <module>
    from roboauto.logger import print_out, print_err
  File "/Users/florian/Downloads/roboauto/robo/lib/python3.9/site-packages/roboauto/logger.py", line 18, in <module>
    def print_and_log(arg, end="\n", file_stream=None, level: int | bool = True):
TypeError: unsupported operand type(s) for |: 'type' and 'type'`

**Comment by jerryfletcher21** [comment]
@FlorianHubl hello, thank you for reporting this error!
This happens because of the python version. The syntax `|: 'type' and 'type'` is only supported by python 3.10 and later.
I forgot to mention it in the README, I will add it now.
You can try again with python 3.10 or later and let me know if it is fixed.
